version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Shop
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - db1

volumes:
  postgres-data: